### ISSUE TITLE
Add web support for LuceneSpinSail

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j-tools#11]
It requires several changes in rdf4j-storage:

- [x] adapt package `rdf4j-lucene-spin`  ref. PR eclipse/rdf4j-storage#31
- [x] create *.ttl layout in `rdf4j-repository-api`ref PR eclipse/rdf4j#965
- [x] add menu layout files  ref PR #14
